import { defineIntegration, createRestHandler, fakeId, fakeArray, fakeEmail, fakeIsoTimestamp, fakeUrl, deriveSeed } from '@weldable/integration-core'

const rest = createRestHandler()

export default defineIntegration({
  id: 'github',
  name: 'GitHub',
  description: 'Manage repositories, issues, pull requests, and code on GitHub.',
  icon: 'github',
  version: 1,
  baseUrl: 'https://api.github.com',
  headers: {
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
  },
  auth: {
    type: 'oauth2',
    test: async (_, ctx) => ctx.http.get('/user').then(r => r.data as Record<string, unknown>),
  },
  nangoScopes: 'repo,read:org,read:user,user:email,gist,workflow',
  nangoCredentialEnvPrefix: 'GH',
  exampleUsage: 'List open pull requests that need review and post a summary to Slack',
  actions: [
    // ── Repositories ─────────────────────────────────────────
    {
      actionId: 'list_user_repos',
      name: 'List my repositories',
      description: 'List all repositories you own or belong to, so you can see what projects are available on your account.',
      intents: [
        'what repos do I have',
        'show my github projects',
        'list all repositories',
        'find a github repo',
        'show all my projects',
        'what github repos am I in',
        'list repos I own',
      ],
      inputFields: [
        {
          name: 'type',
          type: 'string',
          required: false,
          description: 'Filter by type: all, owner, public, private, member.',
          default: 'all',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: created, updated, pushed, full_name.',
          default: 'full_name',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of repositories.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/user/repos',
        paramMapping: { type: 'query', sort: 'query', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'get_repo',
      name: 'Get repository',
      description: 'Fetch details about a specific repository, including its description, stars, forks, default branch, and visibility.',
      intents: [
        'look up a github repo',
        'get repository info',
        'find a github project',
        'check a repo\'s details',
        'show me info about a repo',
        'what is this github repository',
        'get metadata for a repo',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner (user or organization).',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'number', description: 'Repository ID.' },
        { name: 'full_name', type: 'string', description: 'Full name of the repository (owner/repo).' },
        { name: 'html_url', type: 'string', description: 'URL to the repository on GitHub.' },
        { name: 'description', type: 'string', description: 'Repository description.' },
        { name: 'private', type: 'boolean', description: 'Whether the repository is private.' },
        { name: 'default_branch', type: 'string', description: 'Default branch name.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}',
        paramMapping: { owner: 'path', repo: 'path' },
      }),
    },
    {
      actionId: 'create_repo',
      name: 'Create repository',
      description: 'Create a new GitHub repository under your account, with options for visibility and an initial README.',
      intents: [
        'make a new github repo',
        'create a repository',
        'start a new project on github',
        'set up a github repo',
        'initialize a new repo',
        'spin up a new github project',
        'create a private repo',
      ],
      preview: '{name}',
      inputFields: [
        {
          name: 'name',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'description',
          type: 'string',
          required: false,
          description: 'Short description of the repository.',
        },
        {
          name: 'private',
          type: 'boolean',
          required: false,
          description: 'Whether the repository should be private.',
          default: false,
        },
        {
          name: 'auto_init',
          type: 'boolean',
          required: false,
          description: 'Initialize the repository with a README.',
          default: false,
        },
      ],
      outputFields: [
        { name: 'id', type: 'number', description: 'Repository ID.' },
        { name: 'full_name', type: 'string', description: 'Full name of the repository (owner/repo).' },
        { name: 'html_url', type: 'string', description: 'URL to the repository on GitHub.' },
        { name: 'private', type: 'boolean', description: 'Whether the repository is private.' },
        { name: 'clone_url', type: 'string', description: 'HTTPS clone URL.' },
      ],
      execute: rest({
        method: 'POST',
        path: '/user/repos',
        paramMapping: { name: 'body', description: 'body', private: 'body', auto_init: 'body' },
      }),
    },
    {
      actionId: 'list_branches',
      name: 'List branches',
      description: 'List all branches in a repository to see what is being worked on.',
      intents: [
        'what branches exist',
        'show me the branches',
        'see all branches in the repo',
        'list git branches',
        'what feature branches are there',
        'show all branches for this repo',
        'which branches are active',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of branches, each with name and commit SHA.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/branches',
        paramMapping: { owner: 'path', repo: 'path', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'get_branch',
      name: 'Get branch',
      description: 'Get details of a specific branch, including its latest commit, to check its current state.',
      intents: [
        'get branch info',
        'look up a branch',
        'check the status of a branch',
        'what is the latest commit on this branch',
        'show me branch details',
        'inspect a branch',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'branch',
          type: 'string',
          required: true,
          description: 'Branch name.',
        },
      ],
      outputFields: [
        { name: 'name', type: 'string', description: 'Branch name.' },
        { name: 'commit', type: 'object', description: 'Latest commit object with sha and url.' },
        { name: 'protected', type: 'boolean', description: 'Whether the branch is protected.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/branches/{branch}',
        paramMapping: { owner: 'path', repo: 'path', branch: 'path' },
      }),
    },
    {
      actionId: 'list_commits',
      name: 'List commits',
      description: 'Browse the commit history of a repository or branch to see what changes have been made and by whom.',
      intents: [
        'see the commit history',
        'what commits were made',
        'show recent commits',
        'git log for a repo',
        'what changes were pushed recently',
        'show me the history of this branch',
        'who committed to this repo',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'sha',
          type: 'string',
          required: false,
          description: 'Branch name or commit SHA to start listing from.',
        },
        {
          name: 'path',
          type: 'string',
          required: false,
          description: 'Only include commits that changed this file path.',
        },
        {
          name: 'since',
          type: 'string',
          required: false,
          description: 'Only commits after this ISO 8601 date (e.g. 2024-01-01T00:00:00Z).',
        },
        {
          name: 'until',
          type: 'string',
          required: false,
          description: 'Only commits before this ISO 8601 date.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of commits, each with sha, message, author, and url.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/commits',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          sha: 'query',
          path: 'query',
          since: 'query',
          until: 'query',
          per_page: 'query',
          page: 'query',
        },
      }),
      mockExecute: async (_args, ctx) => ({
        items: fakeArray(ctx.seed, 3, (s) => ({
          sha: fakeId(s, 40),
          commit: { message: `Mock commit ${s.slice(-4)}`, author: { name: 'mock-author', date: fakeIsoTimestamp(s) } },
          html_url: fakeUrl(s),
        })),
      }),
    },
    {
      actionId: 'get_commit',
      name: 'Get commit',
      description: 'Fetch a single commit to see what files were changed, the diff, and the author details.',
      intents: [
        'look up a commit',
        'see what changed in a commit',
        'get commit details',
        'what did this commit do',
        'show me the diff for a commit',
        'inspect a specific commit',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'ref',
          type: 'string',
          required: true,
          description: 'Commit SHA, branch name, or tag.',
        },
      ],
      outputFields: [
        { name: 'sha', type: 'string', description: 'Commit SHA.' },
        { name: 'html_url', type: 'string', description: 'URL to the commit on GitHub.' },
        { name: 'commit', type: 'object', description: 'Commit details including message and author.' },
        { name: 'files', type: 'array', description: 'List of files changed in this commit.' },
        { name: 'stats', type: 'object', description: 'Total additions, deletions, and changes.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/commits/{ref}',
        paramMapping: { owner: 'path', repo: 'path', ref: 'path' },
      }),
      mockExecute: async (args, ctx) => ({
        sha: String(args.ref ?? fakeId(ctx.seed, 40)),
        html_url: fakeUrl(ctx.seed),
        commit: { message: 'Mock commit message', author: { name: 'mock-author', email: fakeEmail(ctx.seed), date: fakeIsoTimestamp(ctx.seed) } },
        files: [],
        stats: { total: 2, additions: 1, deletions: 1 },
      }),
    },
    {
      actionId: 'compare_commits',
      name: 'Compare commits',
      description: 'Compare two commits or branches to see what files changed and what commits are different between them.',
      intents: [
        'what changed between two branches',
        'diff between branches',
        'compare main to my branch',
        'what\'s different between two commits',
        'show the changes since the last release',
        'diff two refs',
        'compare feature branch to main',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'basehead',
          type: 'string',
          required: true,
          description: 'Comparison range in "base...head" format (e.g. "main...feature-branch").',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'status', type: 'string', description: 'Comparison status: ahead, behind, diverged, or identical.' },
        { name: 'ahead_by', type: 'number', description: 'Number of commits the head is ahead of the base.' },
        { name: 'behind_by', type: 'number', description: 'Number of commits the head is behind the base.' },
        { name: 'commits', type: 'array', description: 'Commits in the comparison range.' },
        { name: 'files', type: 'array', description: 'Files changed between the two refs.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/compare/{basehead}',
        paramMapping: { owner: 'path', repo: 'path', basehead: 'path', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'list_tags',
      name: 'List tags',
      description: 'List all tags in a repository to see what versions have been marked, useful for tracking releases.',
      intents: [
        'see the release tags',
        'show git tags',
        'list version tags',
        'what versions exist',
        'show all tags in this repo',
        'what tags are on this project',
        'list all version markers',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of tags, each with name and commit SHA.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/tags',
        paramMapping: { owner: 'path', repo: 'path', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'list_releases',
      name: 'List releases',
      description: 'List all published releases for a repository to see what versions have shipped and their release notes.',
      intents: [
        'see github releases',
        'what versions have been released',
        'list published releases',
        'show release history',
        'what has shipped for this project',
        'show me past releases',
        'what versions are out',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of releases, each with id, tag_name, name, html_url, and published_at.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/releases',
        paramMapping: { owner: 'path', repo: 'path', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'create_release',
      name: 'Create release',
      description: 'Publish a new release on GitHub with a version tag, title, and release notes.',
      intents: [
        'publish a release',
        'create a new version',
        'ship a release on github',
        'tag a release',
        'cut a new release',
        'publish version 1.0',
        'make a github release with changelog',
      ],
      preview: '{owner}/{repo}: {tag_name}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'tag_name',
          type: 'string',
          required: true,
          description: 'Tag name for the release (e.g. v1.0.0).',
        },
        {
          name: 'name',
          type: 'string',
          required: false,
          description: 'Release title.',
        },
        {
          name: 'body',
          type: 'string',
          required: false,
          description: 'Release notes (Markdown).',
        },
        {
          name: 'draft',
          type: 'boolean',
          required: false,
          description: 'Create as a draft release.',
          default: false,
        },
        {
          name: 'prerelease',
          type: 'boolean',
          required: false,
          description: 'Mark as a pre-release.',
          default: false,
        },
        {
          name: 'target_commitish',
          type: 'string',
          required: false,
          description: 'Branch or commit SHA to create the tag from. Defaults to the default branch.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'number', description: 'Release ID.' },
        { name: 'html_url', type: 'string', description: 'URL to the release on GitHub.' },
        { name: 'tag_name', type: 'string', description: 'Tag name for the release.' },
        { name: 'name', type: 'string', description: 'Release title.' },
        { name: 'draft', type: 'boolean', description: 'Whether the release is a draft.' },
        { name: 'published_at', type: 'string', description: 'Publication timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/releases',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          tag_name: 'body',
          name: 'body',
          body: 'body',
          draft: 'body',
          prerelease: 'body',
          target_commitish: 'body',
        },
      }),
    },
    {
      actionId: 'get_readme',
      name: 'Get README',
      description: 'Fetch the README file for a repository to understand what the project does and how to use it.',
      intents: [
        'show the README',
        'read the project readme',
        'get the readme file',
        'what does this project do',
        'show me the documentation for this repo',
        'fetch the readme',
        'what is this project about',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'ref',
          type: 'string',
          required: false,
          description: 'Branch, tag, or commit SHA to read from.',
        },
      ],
      outputFields: [
        { name: 'name', type: 'string', description: 'File name (e.g. "README.md").' },
        { name: 'path', type: 'string', description: 'File path in the repository.' },
        { name: 'content', type: 'string', description: 'Base64-encoded file content.' },
        { name: 'html_url', type: 'string', description: 'URL to view the file on GitHub.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/readme',
        paramMapping: { owner: 'path', repo: 'path', ref: 'query' },
      }),
    },
    {
      actionId: 'list_repo_topics',
      name: 'List repository topics',
      description: 'List all topics tagged on a repository to understand how it is categorized.',
      intents: [
        'what topics are on this repo',
        'show repository tags',
        'list the topics for a project',
        'what categories does this repo have',
        'show me the topic labels',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
      ],
      outputFields: [
        { name: 'names', type: 'array', description: 'Array of topic name strings.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/topics',
        paramMapping: { owner: 'path', repo: 'path' },
      }),
    },
    {
      actionId: 'list_contributors',
      name: 'List contributors',
      description: 'List everyone who has contributed to a repository, ranked by commit count.',
      intents: [
        'who contributes to this repo',
        'see all contributors',
        'who has committed to this project',
        'list repo members by commit count',
        'who are the top contributors',
        'show me everyone who has worked on this',
        'get contributor stats',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of contributors, each with login, avatar_url, and contributions count.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/contributors',
        paramMapping: { owner: 'path', repo: 'path', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'list_languages',
      name: 'List languages',
      description: 'List the programming languages used in a repository so you can understand its tech stack.',
      intents: [
        'what languages are used in this repo',
        'show me the tech stack',
        'what programming languages does this project use',
        'list the languages in a repo',
        'how much TypeScript vs JavaScript is there',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
      ],
      outputFields: [
        { name: 'languages', type: 'object', description: 'Map of language names to byte counts.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/languages',
        paramMapping: { owner: 'path', repo: 'path' },
      }),
    },
    // ── Issues ────────────────────────────────────────────────
    {
      actionId: 'list_repo_issues',
      name: 'List issues',
      description: 'List issues for a repository so you can track bugs, feature requests, and tasks.',
      intents: [
        'what are the open issues in this repo',
        'show all issues for a project',
        'list the bugs in this repo',
        'what issues are open',
        'show github issues',
        'list bugs and tasks',
        'see open tickets',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'state',
          type: 'string',
          required: false,
          description: 'Filter by state: open, closed, all.',
          default: 'open',
        },
        {
          name: 'labels',
          type: 'string',
          required: false,
          description: 'Comma-separated label names to filter by.',
        },
        {
          name: 'assignee',
          type: 'string',
          required: false,
          description: 'Filter by assignee username, "none", or "*" for any.',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: created, updated, comments.',
          default: 'created',
        },
        {
          name: 'direction',
          type: 'string',
          required: false,
          description: 'Sort direction: asc or desc.',
          default: 'desc',
        },
        {
          name: 'since',
          type: 'string',
          required: false,
          description: 'Only issues updated at or after this ISO 8601 date.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of issues, each with number, title, state, html_url, and labels.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          state: 'query',
          labels: 'query',
          assignee: 'query',
          sort: 'query',
          direction: 'query',
          since: 'query',
          per_page: 'query',
          page: 'query',
        },
      }),
      mockExecute: async (args, ctx) => ({
        items: fakeArray(ctx.seed, 3, (s) => ({
          number: parseInt(fakeId(s, 4), 16) % 1000 + 1,
          title: `Mock issue ${s.slice(-4)}`,
          state: String(args.state ?? 'open'),
          html_url: fakeUrl(s),
          labels: [],
        })),
      }),
    },
    {
      actionId: 'get_issue',
      name: 'Get issue',
      description: 'Fetch a single issue to read its full description, comments count, labels, and current status.',
      intents: [
        'look up an issue',
        'read an issue',
        'get issue details',
        'see what this ticket is about',
        'open issue number 42',
        'show me the details of this bug',
        'read the full issue',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'issue_number',
          type: 'number',
          required: true,
          description: 'Issue number.',
        },
      ],
      outputFields: [
        { name: 'number', type: 'number', description: 'Issue number.' },
        { name: 'title', type: 'string', description: 'Issue title.' },
        { name: 'state', type: 'string', description: 'Issue state: open or closed.' },
        { name: 'html_url', type: 'string', description: 'URL to the issue on GitHub.' },
        { name: 'body', type: 'string', description: 'Issue body text.' },
        { name: 'labels', type: 'array', description: 'Labels applied to the issue.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues/{issue_number}',
        paramMapping: { owner: 'path', repo: 'path', issue_number: 'path' },
      }),
      mockExecute: async (args, ctx) => ({
        number: typeof args.issue_number === 'number' ? args.issue_number : 42,
        title: 'Mock issue title',
        state: 'open',
        html_url: fakeUrl(ctx.seed),
        body: '',
        labels: [],
      }),
    },
    {
      actionId: 'create_issue',
      name: 'Create issue (bug, feature, task)',
      description: 'File a new issue to report a bug, request a feature, or track a task.',
      intents: [
        'file a bug',
        'open a ticket',
        'report a problem',
        'log an issue',
        'create a task in github',
        'raise a bug',
        'open a new github issue',
        'submit a feature request',
      ],
      preview: '{owner}/{repo}: {title}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'title',
          type: 'string',
          required: true,
          description: 'Issue title.',
        },
        {
          name: 'body',
          type: 'string',
          required: false,
          description: 'Issue body (Markdown).',
        },
        {
          name: 'assignees',
          type: 'object',
          required: false,
          description: 'Array of usernames to assign.',
        },
        {
          name: 'labels',
          type: 'object',
          required: false,
          description: 'Array of label names to apply.',
        },
        {
          name: 'milestone',
          type: 'number',
          required: false,
          description: 'Milestone number to associate with.',
        },
      ],
      outputFields: [
        { name: 'number', type: 'number', description: 'Issue number.' },
        { name: 'html_url', type: 'string', description: 'URL to the issue on GitHub.' },
        { name: 'title', type: 'string', description: 'Issue title.' },
        { name: 'state', type: 'string', description: 'Issue state (open).' },
        { name: 'created_at', type: 'string', description: 'Creation timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/issues',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          title: 'body',
          body: 'body',
          assignees: 'body',
          labels: 'body',
          milestone: 'body',
        },
      }),
      mockExecute: async (args, ctx) => ({
        number: parseInt(fakeId(ctx.seed, 4), 16) % 1000 + 1,
        html_url: fakeUrl(ctx.seed),
        title: String(args.title ?? 'Mock issue title'),
        state: 'open',
        created_at: fakeIsoTimestamp(ctx.seed),
      }),
    },
    {
      actionId: 'update_issue',
      name: 'Update issue',
      description: 'Edit an existing issue to change its title, description, state, labels, or assignees — including closing or reopening it.',
      intents: [
        'close an issue',
        'reopen a ticket',
        'update issue labels',
        'reassign an issue',
        'change issue status',
        'mark this issue as closed',
        'update the issue description',
        'assign this bug to someone',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'issue_number',
          type: 'number',
          required: true,
          description: 'Issue number to update.',
        },
        {
          name: 'title',
          type: 'string',
          required: false,
          description: 'New title.',
        },
        {
          name: 'body',
          type: 'string',
          required: false,
          description: 'New body (Markdown).',
        },
        {
          name: 'state',
          type: 'string',
          required: false,
          description: 'New state: open or closed.',
        },
        {
          name: 'labels',
          type: 'object',
          required: false,
          description: 'Replace labels with this array of label names.',
        },
        {
          name: 'assignees',
          type: 'object',
          required: false,
          description: 'Replace assignees with this array of usernames.',
        },
      ],
      outputFields: [
        { name: 'number', type: 'number', description: 'Issue number.' },
        { name: 'title', type: 'string', description: 'Issue title.' },
        { name: 'state', type: 'string', description: 'Updated issue state: open or closed.' },
        { name: 'html_url', type: 'string', description: 'URL to the issue on GitHub.' },
        { name: 'updated_at', type: 'string', description: 'Last updated timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/issues/{issue_number}',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          issue_number: 'path',
          title: 'body',
          body: 'body',
          state: 'body',
          labels: 'body',
          assignees: 'body',
        },
      }),
      mockExecute: async (args, ctx) => ({
        number: typeof args.issue_number === 'number' ? args.issue_number : 42,
        title: 'Mock updated issue',
        state: String(args.state ?? 'open'),
        html_url: fakeUrl(ctx.seed),
        updated_at: fakeIsoTimestamp(ctx.seed),
      }),
    },
    {
      actionId: 'list_issue_comments',
      name: 'List issue comments',
      description: 'Read all comments on an issue or pull request to follow the discussion.',
      intents: [
        'see comments on an issue',
        'read issue discussion',
        'check notes on a ticket',
        'show me what people said on this issue',
        'get all comments for an issue',
        'read the thread on this bug',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'issue_number',
          type: 'number',
          required: true,
          description: 'Issue number.',
        },
        {
          name: 'since',
          type: 'string',
          required: false,
          description: 'Only comments updated after this ISO 8601 date.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of comments, each with id, body, user login, and created_at.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/issues/{issue_number}/comments',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          issue_number: 'path',
          since: 'query',
          per_page: 'query',
          page: 'query',
        },
      }),
      mockExecute: async (_args, ctx) => ({
        items: fakeArray(ctx.seed, 2, (s) => ({
          id: parseInt(fakeId(s, 8), 16),
          body: `Mock comment ${s.slice(-4)}`,
          user: { login: `user-${s.slice(-4)}` },
          created_at: fakeIsoTimestamp(s),
        })),
      }),
    },
    {
      actionId: 'create_issue_comment',
      name: 'Create issue comment',
      description: 'Post a comment on an issue or pull request to add context, ask a question, or provide an update.',
      intents: [
        'comment on an issue',
        'add a note to a ticket',
        'reply to a github issue',
        'leave a comment on a PR or issue',
        'post a message on this issue',
        'respond to a github thread',
        'add a comment to issue 42',
      ],
      preview: '#{issue_number}: {body}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'issue_number',
          type: 'number',
          required: true,
          description: 'Issue or pull request number.',
        },
        {
          name: 'body',
          type: 'string',
          required: true,
          description: 'Comment text (Markdown).',
        },
      ],
      outputFields: [
        { name: 'id', type: 'number', description: 'Comment ID.' },
        { name: 'html_url', type: 'string', description: 'URL to the comment on GitHub.' },
        { name: 'body', type: 'string', description: 'Comment text.' },
        { name: 'created_at', type: 'string', description: 'Creation timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/issues/{issue_number}/comments',
        paramMapping: { owner: 'path', repo: 'path', issue_number: 'path', body: 'body' },
      }),
      mockExecute: async (args, ctx) => ({
        id: parseInt(fakeId(ctx.seed, 8), 16),
        html_url: fakeUrl(ctx.seed),
        body: String(args.body ?? 'Mock comment'),
        created_at: fakeIsoTimestamp(ctx.seed),
      }),
    },
    {
      actionId: 'list_labels',
      name: 'List labels',
      description: 'List all labels available in a repository so you know what tags can be applied to issues and pull requests.',
      intents: [
        'see labels in this repo',
        'what labels are available',
        'list issue tags',
        'what label options exist',
        'show me all the labels',
        'get the label list for this repo',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of labels, each with id, name, color, and description.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/labels',
        paramMapping: { owner: 'path', repo: 'path', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'create_label',
      name: 'Create label',
      description: 'Add a new label to a repository so it can be applied to issues and pull requests.',
      intents: [
        'add a label to the repo',
        'create a new issue tag',
        'make a github label',
        'add a new category label',
        'set up a label for triage',
        'create a bug label',
      ],
      preview: '{owner}/{repo}: {name}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'name',
          type: 'string',
          required: true,
          description: 'Label name.',
        },
        {
          name: 'color',
          type: 'string',
          required: true,
          description: '6-character hex color code (without #), e.g. "ff0000".',
        },
        {
          name: 'description',
          type: 'string',
          required: false,
          description: 'Short description of the label.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'number', description: 'Label ID.' },
        { name: 'name', type: 'string', description: 'Label name.' },
        { name: 'color', type: 'string', description: 'Label hex color.' },
        { name: 'url', type: 'string', description: 'API URL for the label.' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/labels',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          name: 'body',
          color: 'body',
          description: 'body',
        },
      }),
    },
    {
      actionId: 'add_labels_to_issue',
      name: 'Add labels to issue',
      description: 'Apply one or more labels to an issue to categorize or prioritize it.',
      intents: [
        'tag this issue',
        'add a bug label to this issue',
        'label an issue as priority',
        'apply labels to a ticket',
        'mark an issue with labels',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'issue_number',
          type: 'number',
          required: true,
          description: 'Issue number.',
        },
        {
          name: 'labels',
          type: 'object',
          required: true,
          description: 'Array of label names to add.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'All labels now applied to the issue.' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/issues/{issue_number}/labels',
        paramMapping: { owner: 'path', repo: 'path', issue_number: 'path', labels: 'body' },
      }),
    },
    {
      actionId: 'remove_label_from_issue',
      name: 'Remove label from issue',
      description: 'Remove a specific label from an issue to update its categorization.',
      intents: [
        'remove a label from this issue',
        'untag an issue',
        'strip a label off a ticket',
        'take off the bug label',
        'remove a tag from this issue',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'issue_number',
          type: 'number',
          required: true,
          description: 'Issue number.',
        },
        {
          name: 'name',
          type: 'string',
          required: true,
          description: 'Label name to remove.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'Remaining labels on the issue after removal.' },
      ],
      execute: rest({
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/issues/{issue_number}/labels/{name}',
        paramMapping: { owner: 'path', repo: 'path', issue_number: 'path', name: 'path' },
      }),
    },
    // ── Pull Requests ─────────────────────────────────────────
    {
      actionId: 'list_pull_requests',
      name: 'List pull requests',
      description: 'List pull requests for a repository so you can see what changes are pending review or have been merged.',
      intents: [
        'show open PRs',
        'what pull requests are open',
        'list the pull requests',
        'see PRs waiting for review',
        'show me all pull requests',
        'what PRs need attention',
        'list merged PRs',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'state',
          type: 'string',
          required: false,
          description: 'Filter by state: open, closed, all.',
          default: 'open',
        },
        {
          name: 'head',
          type: 'string',
          required: false,
          description: 'Filter by head branch (format: user:branch).',
        },
        {
          name: 'base',
          type: 'string',
          required: false,
          description: 'Filter by base branch.',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: created, updated, popularity, long-running.',
          default: 'created',
        },
        {
          name: 'direction',
          type: 'string',
          required: false,
          description: 'Sort direction: asc or desc.',
          default: 'desc',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of pull requests, each with number, title, state, html_url, and head/base branch info.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          state: 'query',
          head: 'query',
          base: 'query',
          sort: 'query',
          direction: 'query',
          per_page: 'query',
          page: 'query',
        },
      }),
      mockExecute: async (args, ctx) => ({
        items: fakeArray(ctx.seed, 2, (s) => ({
          number: parseInt(fakeId(s, 4), 16) % 100 + 1,
          title: `Mock PR ${s.slice(-4)}`,
          state: String(args.state ?? 'open'),
          html_url: fakeUrl(s),
          head: { ref: 'feature-branch' },
          base: { ref: 'main' },
        })),
      }),
    },
    {
      actionId: 'get_pull_request',
      name: 'Get pull request',
      description: 'Fetch the full details of a pull request, including its description, reviewers, status checks, and merge state.',
      intents: [
        'look up a PR',
        'get PR details',
        'check the status of a pull request',
        'show me what this PR changes',
        'open pull request 42',
        'read the PR description',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
      ],
      outputFields: [
        { name: 'number', type: 'number', description: 'Pull request number.' },
        { name: 'title', type: 'string', description: 'Pull request title.' },
        { name: 'state', type: 'string', description: 'PR state: open, closed.' },
        { name: 'html_url', type: 'string', description: 'URL to the pull request on GitHub.' },
        { name: 'mergeable', type: 'boolean', description: 'Whether the PR can be merged without conflicts.' },
        { name: 'merged', type: 'boolean', description: 'Whether the PR has been merged.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}',
        paramMapping: { owner: 'path', repo: 'path', pull_number: 'path' },
      }),
      mockExecute: async (args, ctx) => ({
        number: typeof args.pull_number === 'number' ? args.pull_number : 1,
        title: 'Mock pull request',
        state: 'open',
        html_url: fakeUrl(ctx.seed),
        mergeable: true,
        merged: false,
      }),
    },
    {
      actionId: 'create_pull_request',
      name: 'Create pull request (PR)',
      description: 'Open a pull request (PR) to propose merging changes from one branch into another.',
      intents: [
        'open a PR',
        'submit a pull request',
        'propose changes',
        'create a PR from my branch',
        'open a pull request to merge my feature',
        'push my changes for review',
        'request a code review',
      ],
      preview: '{owner}/{repo}: {title}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'title',
          type: 'string',
          required: true,
          description: 'Pull request title.',
        },
        {
          name: 'head',
          type: 'string',
          required: true,
          description: 'Branch containing changes. For cross-repo PRs use "owner:branch" format.',
        },
        {
          name: 'base',
          type: 'string',
          required: true,
          description: 'Branch to merge into (e.g. "main").',
        },
        {
          name: 'body',
          type: 'string',
          required: false,
          description: 'Pull request description (Markdown).',
        },
        {
          name: 'draft',
          type: 'boolean',
          required: false,
          description: 'Create as a draft pull request.',
          default: false,
        },
      ],
      outputFields: [
        { name: 'number', type: 'number', description: 'Pull request number.' },
        { name: 'html_url', type: 'string', description: 'URL to the pull request on GitHub.' },
        { name: 'title', type: 'string', description: 'Pull request title.' },
        { name: 'state', type: 'string', description: 'PR state (open).' },
        { name: 'created_at', type: 'string', description: 'Creation timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          title: 'body',
          head: 'body',
          base: 'body',
          body: 'body',
          draft: 'body',
        },
      }),
      mockExecute: async (args, ctx) => ({
        number: parseInt(fakeId(ctx.seed, 4), 16) % 100 + 1,
        html_url: fakeUrl(ctx.seed),
        title: String(args.title ?? 'Mock pull request'),
        state: 'open',
        created_at: fakeIsoTimestamp(ctx.seed),
      }),
    },
    {
      actionId: 'update_pull_request',
      name: 'Update pull request',
      description: 'Edit a pull request to change its title, description, target branch, or status — including converting to draft or closing it.',
      intents: [
        'update a PR title',
        'change the PR description',
        'mark PR as draft',
        'close a pull request',
        'update the PR body',
        'retarget a PR to a different base branch',
        'convert a PR to draft',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'title',
          type: 'string',
          required: false,
          description: 'New title.',
        },
        {
          name: 'body',
          type: 'string',
          required: false,
          description: 'New description (Markdown).',
        },
        {
          name: 'state',
          type: 'string',
          required: false,
          description: 'New state: open or closed.',
        },
        {
          name: 'base',
          type: 'string',
          required: false,
          description: 'New base branch to merge into.',
        },
      ],
      outputFields: [
        { name: 'number', type: 'number', description: 'Pull request number.' },
        { name: 'title', type: 'string', description: 'Updated PR title.' },
        { name: 'state', type: 'string', description: 'Updated PR state: open or closed.' },
        { name: 'html_url', type: 'string', description: 'URL to the pull request on GitHub.' },
        { name: 'updated_at', type: 'string', description: 'Last updated timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'PATCH',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          title: 'body',
          body: 'body',
          state: 'body',
          base: 'body',
        },
      }),
    },
    {
      actionId: 'list_pr_comments',
      name: 'List PR review comments',
      description: 'List all inline review comments on a pull request to see the code-level feedback left by reviewers.',
      intents: [
        'see comments on a PR',
        'read PR feedback',
        'check PR discussion',
        'show me the inline comments on this PR',
        'what did reviewers say on this pull request',
        'list code review comments',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of review comments, each with id, body, path, line, and user login.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}/comments',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          per_page: 'query',
          page: 'query',
        },
      }),
    },
    {
      actionId: 'create_pr_review_comment',
      name: 'Create PR review comment',
      description: 'Leave an inline comment on a specific line of a pull request diff to give targeted code feedback.',
      intents: [
        'comment on a PR',
        'leave feedback on a pull request',
        'add a note to a PR',
        'add an inline code comment to a PR',
        'comment on a specific line in a pull request',
        'suggest a change on this line',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'body',
          type: 'string',
          required: true,
          description: 'Comment text (Markdown).',
        },
        {
          name: 'path',
          type: 'string',
          required: true,
          description: 'Relative file path to comment on.',
        },
        {
          name: 'line',
          type: 'number',
          required: true,
          description: 'Line number in the file to comment on.',
        },
        {
          name: 'commit_id',
          type: 'string',
          required: false,
          description: 'SHA of the commit to comment on.',
        },
        {
          name: 'side',
          type: 'string',
          required: false,
          description: 'Side of the diff: LEFT or RIGHT.',
          default: 'RIGHT',
        },
      ],
      outputFields: [
        { name: 'id', type: 'number', description: 'Review comment ID.' },
        { name: 'html_url', type: 'string', description: 'URL to the comment on GitHub.' },
        { name: 'body', type: 'string', description: 'Comment text.' },
        { name: 'path', type: 'string', description: 'File path the comment is on.' },
        { name: 'created_at', type: 'string', description: 'Creation timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}/comments',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          body: 'body',
          path: 'body',
          line: 'body',
          commit_id: 'body',
          side: 'body',
        },
      }),
    },
    {
      actionId: 'list_pr_reviews',
      name: 'List PR reviews',
      description: 'List all formal reviews submitted on a pull request to see who approved, requested changes, or left comments.',
      intents: [
        'see PR reviews',
        'check review status',
        'who reviewed this PR',
        'has this pull request been approved',
        'show me the reviews on this PR',
        'who requested changes on this PR',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of reviews, each with id, state (APPROVED, CHANGES_REQUESTED, COMMENTED), user login, and submitted_at.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}/reviews',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          per_page: 'query',
          page: 'query',
        },
      }),
    },
    {
      actionId: 'create_pr_review',
      name: 'Create PR review',
      description: 'Submit a formal review on a pull request — approve it, request changes, or leave a comment-only review.',
      intents: [
        'approve a PR',
        'request changes on a PR',
        'review a pull request',
        'leave a review',
        'sign off on a PR',
        'block a PR with change requests',
        'submit my review',
      ],
      preview: '#{pull_number}: {event}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'event',
          type: 'string',
          required: true,
          description: 'Review action: APPROVE, REQUEST_CHANGES, or COMMENT.',
        },
        {
          name: 'body',
          type: 'string',
          required: false,
          description: 'Review summary comment (Markdown). Required when event is REQUEST_CHANGES or COMMENT.',
        },
        {
          name: 'comments',
          type: 'object',
          required: false,
          description: 'Array of inline review comment objects with path, line, and body.',
        },
      ],
      outputFields: [
        { name: 'id', type: 'number', description: 'Review ID.' },
        { name: 'state', type: 'string', description: 'Review state: APPROVED, CHANGES_REQUESTED, or COMMENTED.' },
        { name: 'html_url', type: 'string', description: 'URL to the review on GitHub.' },
        { name: 'submitted_at', type: 'string', description: 'Submission timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}/reviews',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          event: 'body',
          body: 'body',
          comments: 'body',
        },
      }),
    },
    {
      actionId: 'merge_pull_request',
      name: 'Merge pull request',
      description: 'Merge an approved pull request into the target branch to ship the changes.',
      intents: [
        'merge a PR',
        'ship a pull request',
        'land a PR',
        'accept and merge changes',
        'close the PR and merge',
        'squash and merge this PR',
        'merge this into main',
      ],
      preview: '#{pull_number}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'commit_title',
          type: 'string',
          required: false,
          description: 'Title for the merge commit.',
        },
        {
          name: 'commit_message',
          type: 'string',
          required: false,
          description: 'Extra detail for the merge commit message.',
        },
        {
          name: 'merge_method',
          type: 'string',
          required: false,
          description: 'Merge strategy: merge, squash, or rebase.',
          default: 'merge',
        },
      ],
      outputFields: [
        { name: 'sha', type: 'string', description: 'SHA of the merge commit.' },
        { name: 'merged', type: 'boolean', description: 'Whether the merge succeeded.' },
        { name: 'message', type: 'string', description: 'Merge result message.' },
      ],
      execute: rest({
        method: 'PUT',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}/merge',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          commit_title: 'body',
          commit_message: 'body',
          merge_method: 'body',
        },
      }),
      mockExecute: async (_args, ctx) => ({
        sha: fakeId(ctx.seed, 40),
        merged: true,
        message: 'Pull request successfully merged.',
      }),
    },
    {
      actionId: 'list_pr_files',
      name: 'List PR files',
      description: 'List all files changed in a pull request so you can see what was modified, added, or deleted.',
      intents: [
        'what files changed in this PR',
        'show me the diff files for a pull request',
        'list changed files in a PR',
        'what was modified in this pull request',
        'see the file changes for PR 42',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of changed files, each with filename, status (added/modified/removed), additions, and deletions.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}/files',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          per_page: 'query',
          page: 'query',
        },
      }),
    },
    {
      actionId: 'list_pr_commits',
      name: 'List PR commits',
      description: 'List all commits included in a pull request to understand the full set of changes being proposed.',
      intents: [
        'what commits are in this PR',
        'show me the commits for a pull request',
        'list the changes in this PR',
        'how many commits does this PR have',
        'get all commits for PR 42',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'pull_number',
          type: 'number',
          required: true,
          description: 'Pull request number.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of commits in the PR, each with sha, message, and author.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/pulls/{pull_number}/commits',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          pull_number: 'path',
          per_page: 'query',
          page: 'query',
        },
      }),
    },
    // ── Search ────────────────────────────────────────────────
    {
      actionId: 'search_repos',
      name: 'Search repositories',
      description: 'Search GitHub for repositories matching a keyword or set of filters, useful for discovering projects.',
      intents: [
        'search for repos on github',
        'find a github project',
        'look up repos matching',
        'find open source projects',
        'search github for a library',
        'find repos by language',
        'discover projects on github',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: true,
          description: 'Search query using GitHub search syntax (e.g. "language:typescript stars:>100").',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: stars, forks, help-wanted-issues, updated.',
        },
        {
          name: 'order',
          type: 'string',
          required: false,
          description: 'Sort order: asc or desc.',
          default: 'desc',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'total_count', type: 'number', description: 'Total number of results.' },
        { name: 'items', type: 'array', description: 'Matching results.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/search/repositories',
        paramMapping: { q: 'query', sort: 'query', order: 'query', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'search_code',
      name: 'Search code',
      description: 'Search for code across GitHub repositories to find where a function, pattern, or string is used.',
      intents: [
        'find where this function is defined',
        'search for code across github',
        'look for this string in the codebase',
        'find all files that use',
        'search for a function on github',
        'where is this method called',
        'find code examples on github',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: true,
          description: 'Search query. Scope with qualifiers like repo:, org:, or user: (e.g. "addClass repo:jquery/jquery").',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: indexed.',
        },
        {
          name: 'order',
          type: 'string',
          required: false,
          description: 'Sort order: asc or desc.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'total_count', type: 'number', description: 'Total number of results.' },
        { name: 'items', type: 'array', description: 'Matching results.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/search/code',
        paramMapping: { q: 'query', sort: 'query', order: 'query', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'search_issues',
      name: 'Search issues and PRs',
      description: 'Search for issues and pull requests across GitHub repositories to find bugs, tasks, or changes by keyword or filter.',
      intents: [
        'search github issues',
        'find issues across repos',
        'look for bugs mentioning',
        'search tickets',
        'find open issues about a topic',
        'search for PRs with a specific label',
        'look up issues assigned to me',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: true,
          description: 'Search query (e.g. "is:issue is:open label:bug repo:owner/name").',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: comments, reactions, created, updated.',
        },
        {
          name: 'order',
          type: 'string',
          required: false,
          description: 'Sort order: asc or desc.',
          default: 'desc',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'total_count', type: 'number', description: 'Total number of results.' },
        { name: 'items', type: 'array', description: 'Matching results.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/search/issues',
        paramMapping: { q: 'query', sort: 'query', order: 'query', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'search_users',
      name: 'Search users',
      description: 'Search for GitHub users and organizations by keyword to discover developers or teams.',
      intents: [
        'find a github user',
        'look up a developer on github',
        'search for github accounts',
        'find people on github by location',
        'search for an organization',
        'who on github works with Python',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: true,
          description: 'Search query (e.g. "location:london language:python").',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: followers, repositories, joined.',
        },
        {
          name: 'order',
          type: 'string',
          required: false,
          description: 'Sort order: asc or desc.',
          default: 'desc',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'total_count', type: 'number', description: 'Total number of results.' },
        { name: 'items', type: 'array', description: 'Matching results.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/search/users',
        paramMapping: { q: 'query', sort: 'query', order: 'query', per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'search_commits',
      name: 'Search commits',
      description: 'Search for commits across GitHub repositories to find specific changes by message, author, or date.',
      intents: [
        'search for commits mentioning a fix',
        'find commits by a specific author',
        'look for a commit across repos',
        'search commit history on github',
        'find commits that mention a bug',
      ],
      inputFields: [
        {
          name: 'q',
          type: 'string',
          required: true,
          description: 'Search query (e.g. "fix bug repo:owner/name author:username").',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: author-date, committer-date.',
        },
        {
          name: 'order',
          type: 'string',
          required: false,
          description: 'Sort order: asc or desc.',
          default: 'desc',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'total_count', type: 'number', description: 'Total number of results.' },
        { name: 'items', type: 'array', description: 'Matching results.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/search/commits',
        paramMapping: { q: 'query', sort: 'query', order: 'query', per_page: 'query', page: 'query' },
      }),
    },
    // ── Users & Organizations ─────────────────────────────────
    {
      actionId: 'get_authenticated_user',
      name: 'Get my GitHub profile',
      description: 'Fetch the profile of the currently authenticated GitHub account, including your username, email, and public info.',
      intents: [
        'who am I logged in as',
        'check my github account',
        'get my github profile',
        'what github user am I',
        'show my github info',
        'what is my github username',
      ],
      inputFields: [],
      outputFields: [
        { name: 'login', type: 'string', description: 'GitHub username.' },
        { name: 'id', type: 'number', description: 'User ID.' },
        { name: 'name', type: 'string', description: 'Display name.' },
        { name: 'email', type: 'string', description: 'Public email address.' },
        { name: 'html_url', type: 'string', description: 'URL to profile on GitHub.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/user',
        paramMapping: {},
      }),
    },
    {
      actionId: 'get_user',
      name: 'Get user',
      description: 'Fetch a public GitHub user\'s profile to see their bio, public repos, followers, and activity.',
      intents: [
        'get someone\'s github profile',
        'look up a github user',
        'check a github account',
        'who is this github user',
        'show me the profile for a developer',
        'find a user\'s github page',
      ],
      inputFields: [
        {
          name: 'username',
          type: 'string',
          required: true,
          description: 'GitHub username.',
        },
      ],
      outputFields: [
        { name: 'login', type: 'string', description: 'GitHub username.' },
        { name: 'id', type: 'number', description: 'User ID.' },
        { name: 'name', type: 'string', description: 'Display name.' },
        { name: 'html_url', type: 'string', description: 'URL to profile on GitHub.' },
        { name: 'public_repos', type: 'number', description: 'Number of public repositories.' },
        { name: 'followers', type: 'number', description: 'Number of followers.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/users/{username}',
        paramMapping: { username: 'path' },
      }),
    },
    {
      actionId: 'list_orgs',
      name: 'List organizations',
      description: 'List all GitHub organizations the authenticated user belongs to.',
      intents: [
        'what github orgs am I in',
        'show my organizations',
        'list my github organizations',
        'what teams am I part of on github',
        'show all orgs I belong to',
      ],
      inputFields: [
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of organizations, each with login, id, and description.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/user/orgs',
        paramMapping: { per_page: 'query', page: 'query' },
      }),
    },
    {
      actionId: 'list_org_repos',
      name: 'List organization repositories',
      description: 'List all repositories belonging to a GitHub organization so you can see what projects it maintains.',
      intents: [
        'what repos does this org have',
        'show all repos for an organization',
        'list projects in a github org',
        'what does this github organization own',
        'show me all repos under an org',
      ],
      inputFields: [
        {
          name: 'org',
          type: 'string',
          required: true,
          description: 'Organization name.',
        },
        {
          name: 'type',
          type: 'string',
          required: false,
          description: 'Filter by type: all, public, private, forks, sources, member.',
          default: 'all',
        },
        {
          name: 'sort',
          type: 'string',
          required: false,
          description: 'Sort by: created, updated, pushed, full_name.',
          default: 'created',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'items', type: 'array', description: 'List of repositories in the organization.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/orgs/{org}/repos',
        paramMapping: { org: 'path', type: 'query', sort: 'query', per_page: 'query', page: 'query' },
      }),
    },
    // ── File Contents ─────────────────────────────────────────
    {
      actionId: 'get_file_contents',
      name: 'Get file contents',
      description: 'Read the contents of a file or list a directory in a repository.',
      intents: [
        'read a file from github',
        'get the contents of a file in a repo',
        'show me the code in a file',
        'look up a file in the repo',
        'fetch a file from a branch',
        'read the config file in this repo',
        'show me what\'s in this file',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'path',
          type: 'string',
          required: true,
          description: 'File path within the repository (e.g. "src/index.ts").',
        },
        {
          name: 'ref',
          type: 'string',
          required: false,
          description: 'Branch, tag, or commit SHA to read from.',
        },
      ],
      outputFields: [
        { name: 'name', type: 'string', description: 'File or directory name.' },
        { name: 'path', type: 'string', description: 'Path within the repository.' },
        { name: 'sha', type: 'string', description: 'File blob SHA (needed for updates).' },
        { name: 'content', type: 'string', description: 'Base64-encoded file content (if a file).' },
        { name: 'html_url', type: 'string', description: 'URL to view the file on GitHub.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/contents/{path}',
        paramMapping: { owner: 'path', repo: 'path', path: 'path', ref: 'query' },
      }),
      mockExecute: async (args, ctx) => ({
        name: String(args.path ?? 'file.txt').split('/').at(-1) ?? 'file.txt',
        path: String(args.path ?? 'file.txt'),
        sha: fakeId(ctx.seed, 40),
        content: '',
        html_url: fakeUrl(ctx.seed),
      }),
    },
    {
      actionId: 'create_or_update_file',
      name: 'Create or update file',
      description: 'Commit a new or updated file directly to a repository branch.',
      intents: [
        'add a file to the repo',
        'edit a file on github',
        'commit a file change',
        'update a file in the repository',
        'write a file to a branch',
        'save changes to a file in github',
        'push a file to the repo',
      ],
      preview: '{owner}/{repo}: {path}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'path',
          type: 'string',
          required: true,
          description: 'File path within the repository.',
        },
        {
          name: 'message',
          type: 'string',
          required: true,
          description: 'Commit message.',
        },
        {
          name: 'content',
          type: 'string',
          required: true,
          description: 'New file content, base64-encoded.',
        },
        {
          name: 'sha',
          type: 'string',
          required: false,
          description: 'SHA of the file being replaced. Required when updating an existing file.',
        },
        {
          name: 'branch',
          type: 'string',
          required: false,
          description: 'Branch to commit to. Defaults to the repository\'s default branch.',
        },
      ],
      outputFields: [
        { name: 'content', type: 'object', description: 'File metadata after the commit, including path, sha, and html_url.' },
        { name: 'commit', type: 'object', description: 'Commit details including sha and html_url.' },
      ],
      execute: rest({
        method: 'PUT',
        path: '/repos/{owner}/{repo}/contents/{path}',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          path: 'path',
          message: 'body',
          content: 'body',
          sha: 'body',
          branch: 'body',
        },
      }),
      mockExecute: async (args, ctx) => ({
        commit: { sha: fakeId(ctx.seed, 40), message: String(args.message ?? 'Mock commit'), html_url: fakeUrl(ctx.seed) },
        content: { path: String(args.path ?? 'file.txt'), sha: fakeId(deriveSeed(ctx.seed, 'blob'), 40) },
      }),
    },
    {
      actionId: 'delete_file',
      name: 'Remove file',
      description: 'Remove a file from a repository by committing its deletion.',
      intents: [
        'remove a file from the repo',
        'delete a file from github',
        'commit a file deletion',
        'erase a file from the repository',
        'delete this file from the branch',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'path',
          type: 'string',
          required: true,
          description: 'File path within the repository.',
        },
        {
          name: 'message',
          type: 'string',
          required: true,
          description: 'Commit message.',
        },
        {
          name: 'sha',
          type: 'string',
          required: true,
          description: 'SHA of the file to delete.',
        },
        {
          name: 'branch',
          type: 'string',
          required: false,
          description: 'Branch to commit to. Defaults to the repository\'s default branch.',
        },
      ],
      outputFields: [
        { name: 'commit', type: 'object', description: 'Commit details for the deletion, including sha and html_url.' },
      ],
      execute: rest({
        method: 'DELETE',
        path: '/repos/{owner}/{repo}/contents/{path}',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          path: 'path',
          message: 'body',
          sha: 'body',
          branch: 'body',
        },
      }),
    },
    // ── Actions / Workflows ───────────────────────────────────
    {
      actionId: 'list_workflow_runs',
      name: 'List workflow runs',
      description: 'List recent GitHub Actions runs for a repository to check CI/CD status and history.',
      intents: [
        'see recent CI runs',
        'check github actions status',
        'list workflow run history',
        'what workflows have run recently',
        'show me the github actions runs',
        'did my CI pass',
        'show failed workflow runs',
      ],
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'status',
          type: 'string',
          required: false,
          description: 'Filter by status: completed, in_progress, queued, failure, success, cancelled, etc.',
        },
        {
          name: 'branch',
          type: 'string',
          required: false,
          description: 'Filter by branch name.',
        },
        {
          name: 'per_page',
          type: 'number',
          required: false,
          description: 'Results per page (max 100).',
          default: 30,
        },
        {
          name: 'page',
          type: 'number',
          required: false,
          description: 'Page number.',
        },
      ],
      outputFields: [
        { name: 'total_count', type: 'number', description: 'Total number of workflow runs.' },
        { name: 'workflow_runs', type: 'array', description: 'List of workflow runs, each with id, name, status, conclusion, and html_url.' },
      ],
      execute: rest({
        method: 'GET',
        path: '/repos/{owner}/{repo}/actions/runs',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          status: 'query',
          branch: 'query',
          per_page: 'query',
          page: 'query',
        },
      }),
    },
    {
      actionId: 'trigger_workflow_dispatch',
      name: 'Run workflow',
      description: 'Manually trigger a GitHub Actions workflow to run, useful for deployments or one-off automation.',
      intents: [
        'run a github action',
        'manually trigger a workflow',
        'kick off a CI pipeline',
        'run CI',
        'trigger a deployment workflow',
        'start a workflow manually',
        'fire off a github action',
        'run the deploy workflow',
      ],
      preview: '{owner}/{repo}: {workflow_id}',
      inputFields: [
        {
          name: 'owner',
          type: 'string',
          required: true,
          description: 'Repository owner.',
        },
        {
          name: 'repo',
          type: 'string',
          required: true,
          description: 'Repository name.',
        },
        {
          name: 'workflow_id',
          type: 'string',
          required: true,
          description: 'Workflow file name (e.g. "deploy.yml") or numeric workflow ID.',
        },
        {
          name: 'ref',
          type: 'string',
          required: true,
          description: 'Branch or tag to run the workflow on.',
        },
        {
          name: 'inputs',
          type: 'object',
          required: false,
          description: 'Key/value pairs of workflow input parameters.',
        },
      ],
      outputFields: [
        { name: 'ok', type: 'boolean', description: 'True if the workflow was triggered successfully.' },
      ],
      execute: rest({
        method: 'POST',
        path: '/repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches',
        paramMapping: {
          owner: 'path',
          repo: 'path',
          workflow_id: 'path',
          ref: 'body',
          inputs: 'body',
        },
      }),
    },
    // ── Gists ─────────────────────────────────────────────────
    {
      actionId: 'create_gist',
      name: 'Create gist',
      description: 'Create a new GitHub Gist to quickly share a snippet of code or text.',
      intents: [
        'create a gist',
        'share a code snippet on github',
        'post a gist',
        'make a public gist',
        'save a snippet to github gists',
        'share some code as a gist',
      ],
      preview: '{description}',
      inputFields: [
        {
          name: 'files',
          type: 'object',
          required: true,
          description: 'Map of filename to file content object, e.g. {"hello.txt": {"content": "Hello World"}}.',
        },
        {
          name: 'description',
          type: 'string',
          required: false,
          description: 'Description of the gist.',
        },
        {
          name: 'public',
          type: 'boolean',
          required: false,
          description: 'Whether the gist is public.',
          default: false,
        },
      ],
      outputFields: [
        { name: 'id', type: 'string', description: 'Gist ID.' },
        { name: 'html_url', type: 'string', description: 'URL to the gist on GitHub.' },
        { name: 'description', type: 'string', description: 'Gist description.' },
        { name: 'public', type: 'boolean', description: 'Whether the gist is public.' },
        { name: 'created_at', type: 'string', description: 'Creation timestamp (ISO 8601).' },
      ],
      execute: rest({
        method: 'POST',
        path: '/gists',
        paramMapping: { files: 'body', description: 'body', public: 'body' },
      }),
    },
  ],
})
